apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}subscription
  labels:
    app: {{ .Values.appName }}subscription
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}subscription
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}subscription
        tier: frontend
    spec: # Pod spec
      containers:
      - name: subscription-container
        image: "{{ .Values.image_subscription.name }}:{{ .Values.image_subscription.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}database
  labels:
    app: {{ .Values.appName }}database
spec:
  replicas: {{ .Values.replicas_db }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}database
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}database
        tier: frontend
    spec: # Pod spec
      containers:
      - name: database-container
        image: "{{ .Values.image_database.name }}:{{ .Values.image_database.tag }}"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_PORT
            value: "3306"
          - name: MARIADB_USER
            value: "username"
          - name: MARIADB_ROOT_PASSWORD
            value: "123456"
          - name: MARIADB_DATABASE
            value: "database"
          - name: MARIADB_PASSWORD
            value: "123456"
          - name: HOST_CACHE_SIZE
            value: "0"
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"